---
functional:
  - На сайте должна быть возможность регистрации и авторизации пользователей
  - Игроки должны иметь возможность видеть друг у друга редактор с кодом, вывод тестов, и возможность менять язык программирования во время решения
  - У пользователей должна быть возможность играть в игру с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - На сайте должна быть возможность выбрать игру по уровню сложности 
  - На сайте должна быть возможность выбора определенной игры, если игра не выбрана пользователями - она будет подобрана случайным образом
  - Другие пользователи должны иметь возможность следить за ходом игры
  - На сайте должен быть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи. Редактор для ввода кода выглядит как проигрыватель
  - У пользователей должна быть возможность получать очки за побежденные игры, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Задачи даны на двух языках — русском и английском
implicit:
  - У игроков не должно быть доступа к редактору с кодом соперников
  - Игроки должны иметь идентификатор того являются они ботами или реальными пользователями
  - Пользователи должны получать email уведомление - приглашение в случае, если другой пользователь пригласил их играть
  - При случайном подборе игры - она не должна повторяться
  - Возможность случайного подбора соперника, где сайт сам выберет его исходя из пользователей онлайн и ботов 
